apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: gameshelf
spec:
  chart:
    name: gameshelf
    chartVersion: "0.0.0"
  values:
    adminSecret: repl{{ ConfigOption `admin_secret`}}
    siteName: repl{{ ConfigOption `site_name`}}
    siteColor: repl{{ ConfigOption `site_color`}}
    customBrandingEnabled: repl{{ LicenseFieldValue `custom_branding_enabled` }}
    siteLogoUrl: 'repl{{ ConfigOption "site_logo_url" }}'
    imageProxy:
      host: ""
    service:
      type: NodePort
      nodePort: 30081
    image:
      registry: 'repl{{ ReplicatedImageRegistry "ghcr.io" }}'
      repository: 'aa-replicated/gameshelf'
      pullPolicy: IfNotPresent
    replicated:
      image:
        registry: 'repl{{ ReplicatedImageRegistry "proxy.replicated.com" true }}'
    postgresql:
      enabled: 'repl{{ ConfigOption "db_type" | eq "embedded" }}'
      auth:
        password: 'repl{{ ConfigOption "db_password_generated" }}'
      image:
        registry: 'repl{{ ReplicatedImageRegistry "index.docker.io" }}'
    externalDatabase:
      host: 'repl{{ ConfigOption "db_host" }}'
      port: 'repl{{ ConfigOption "db_port" }}'
      database: 'repl{{ ConfigOption "db_name" }}'
      username: 'repl{{ ConfigOption "db_user" }}'
      password: 'repl{{ ConfigOption "db_password" }}'
    redis:
      image:
        registry: 'repl{{ ReplicatedImageRegistry "index.docker.io" }}'
  builder:
    image:
      registry: "ghcr.io"
      repository: "aa-replicated/gameshelf"
    replicated:
      image:
        registry: "proxy.replicated.com"
        repository: "library/replicated-sdk-image"
    postgresql:
      image:
        registry: "docker.io"
    redis:
      image:
        registry: "docker.io"
