apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: gameshelf
spec:
  chart:
    name: gameshelf
    chartVersion: "0.0.0"
  values:
    gameshelf-sdk:
      integration:
        licenseID: repl{{ LicenseFieldValue `licenseID` }}
        enabled: true
    adminSecret: repl{{ ConfigOption `admin_secret`}}
    siteName: repl{{ ConfigOption `site_name`}}
  builder:
    image:
      tag: latest
