apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: gameshelf
spec:
  chart:
    name: gameshelf
    chartVersion: "0.0.0"
  values:
    replicated:
      integrationLicenseID: repl{{ LicenseFieldValue `licenseID` }}
    adminSecret: repl{{ ConfigOption `admin_secret`}}
    siteName: repl{{ ConfigOption `site_name`}}
    siteColor: repl{{ ConfigOption `site_color`}}
    customBrandingEnabled: repl{{ LicenseFieldValue `custom_branding_enabled` }}
    imageProxy:
      host: ""
    image:
      pullPolicy: IfNotPresent
    postgresql:
      image:
        registry: ""
    redis:
      image:
        registry: ""
  builder:
    postgresql:
      image:
        registry: "docker.io"
    redis:
      image:
        registry: "docker.io"
