{{- if eq .Values.tls.mode "auto" -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.tls.auto.issuer | default "letsencrypt-prod" }}
  labels:
    {{- include "gameshelf.labels" . | nindent 4 }}
spec:
  acme:
    email: {{ .Values.tls.auto.issuerEmail | quote }}
    server: {{ if eq (.Values.tls.auto.issuer | default "letsencrypt-prod") "letsencrypt-staging" -}}
      https://acme-staging-v02.api.letsencrypt.org/directory
    {{- else -}}
      https://acme-v02.api.letsencrypt.org/directory
    {{- end }}
    privateKeySecretRef:
      name: {{ .Values.tls.auto.issuer | default "letsencrypt-prod" }}-account-key
    solvers:
      - http01:
          ingress:
            ingressClassName: "traefik"
{{ end }}
{{- if eq .Values.tls.mode "selfsigned" -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
  labels:
    {{- include "gameshelf.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{ end }}
