apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gameshelf.fullname" . }}
  labels:
    {{- include "gameshelf.labels" . | nindent 4 }}
data:
  port: "8080"
  site-name: {{ .Values.siteName | quote }}
  site-color: {{ .Values.siteColor | default "#3B82F6" | quote }}
  custom-branding-enabled: {{ .Values.customBrandingEnabled | quote }}
  site-logo-url: {{ .Values.siteLogoUrl | quote }}
