{{- if or .Values.ingress.enabled (ne .Values.tls.mode "none") -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "gameshelf.fullname" . }}
  labels:
    {{- include "gameshelf.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if eq .Values.tls.mode "auto" }}
    cert-manager.io/cluster-issuer: {{ .Values.tls.auto.issuer | default "letsencrypt-prod" | quote }}
    {{- end }}
    {{- if eq .Values.tls.mode "selfsigned" }}
    cert-manager.io/cluster-issuer: "selfsigned-issuer"
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "traefik" | quote }}
  {{- if ne .Values.tls.mode "none" }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ if eq .Values.tls.mode "manual" -}}
        {{ .Values.tls.manual.secretName | quote }}
      {{- else if eq .Values.tls.mode "selfsigned" -}}
        "{{ include "gameshelf.fullname" . }}-tls-selfsigned"
      {{- else -}}
        "{{ include "gameshelf.fullname" . }}-tls"
      {{- end }}
  {{- else if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if ne .Values.tls.mode "none" }}
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "gameshelf.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
    {{- else }}
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "gameshelf.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
