apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gameshelf.fullname" . }}
  labels:
    {{- include "gameshelf.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-secret: {{ .Values.adminSecret | quote }}
  database-url: {{ include "gameshelf.databaseUrl" . | quote }}
  redis-url: {{ include "gameshelf.redisUrl" . | quote }}
